name: flyheadsup
favicon: null
layout_spectrum: 0.47424497990868986
typography_spectrum: 0.6823239855002612
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2160362177528441
  lightness: 0.27958331536501646
  saturation: 0.734190532239154
  rhythmicContrast: 0.2816600608639419
purpose: []
